### ISSUE TITLE
get_mac_address from p2pd.netifaces_xtra fails on android.

### ISSUE THREAD

**Issue by magowiz** [robertsdotpm/p2pd#12] opened 2023-12-28 17:09 UTC
Hi,
I'm trying to run your library on android, I found out that in this method I get a KeyError:
```
def get_mac_address(name, netifaces):
    return netifaces.ifaddresses(name)[netifaces.AF_LINK][0]["addr"]
```    
I was able to try the netifaces library in a simple loop I made and I figured out that in android, the right index is not 17, the one coming from `netifaces.AF_LINK` but 2.
My simple code:
```
import netifaces
import pprint

for iface in netifaces.interfaces():
	print(iface)
	try:
		pprint.pprint(netifaces.ifaddresses(iface))
		print(netifaces.ifaddresses(iface)[netifaces.AF_LINK])
	except KeyError:
		print(iface, " error")
		continue
```
 For every interface I get error, reading the output of pprint I can see that there is not 17 but typically in number 2 there is a ipv4 address.
 
 I don't know if you are interested on making it work also in android, by the way I thought it could be a good thing to at least tell this to you.
 
 Regards
magowiz

**Comment by robertsdotpm** [comment] 2023-12-29 01:36
Hello, yes please do keep reporting bugs. My next sprint on the project I plan to try increase test coverage massively and fix more bugs that people report. Aiming for much better stability. I need to setup my test infrastructure better though because when you're trying to target multiple OSes and even Android it needs to be easy to run the tests.

I will get around to fixing your issue eventually. For now I can say: try to call init_p2pd() also before using netifaces stuff. My code isn't really designed to use netifaces directly and network interface stuff is done through the Interface class. To use the Interface class you can call await Interface() to load a default interface. Or for a specific one: await Interface("e.g.: wlan0"). This library is built to use coroutines so it also helps to know that. 

Thanks for taking the effort to report this. I'll keep all issues open until they're fixed.

**Comment by magowiz** [comment] 2023-12-29 13:53
Sorry I realized that you are not searching for ip address in that case but for mac addresses, so the index 2 is wrong because contains IPs. By the way I tried to run this code, putting also init_p2pd() at the beginning, but with no luck:
the code I ran:
```
from p2pd import *

async def example():
    # Start the default interface.
    init_p2pd()
    i = await Interface()
    #
    # Load additional NAT details.
    # Restrict, random port NAT assumed by default.
    
    await i.load_nat()
    #
    # Show the interface details.
    
    print(i)

if __name__ == '__main__':
    async_test(example)
```
the error:
```
/storage/emulated/0/Code/1-network-interfaces.py:5: RuntimeWarning: coroutine 'init_p2pd' was never awaited
Coroutine created at (most recent call last)
  File "/storage/emulated/0/Code/1-network-interfaces.py", line 18, in <module>
    async_test(example)
  File "/data/data/com.termux/files/home/.virtualenvs/p2pd/lib/python3.11/site-packages/p2pd/utils.py", line 609, in async_test
    loop.run_until_complete(f())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/storage/emulated/0/Code/1-network-interfaces.py", line 5, in example
    init_p2pd()
  init_p2pd()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/storage/emulated/0/Code/1-network-interfaces.py", line 18, in <module>
    async_test(example)
  File "/data/data/com.termux/files/home/.virtualenvs/p2pd/lib/python3.11/site-packages/p2pd/utils.py", line 609, in async_test
    loop.run_until_complete(f())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Code/1-network-interfaces.py", line 6, in example
    i = await Interface()
        ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/.virtualenvs/p2pd/lib/python3.11/site-packages/p2pd/interface.py", line 363, in start
    self.load_if_info()
  File "/data/data/com.termux/files/home/.virtualenvs/p2pd/lib/python3.11/site-packages/p2pd/interface.py", line 238, in load_if_info
    self.mac = get_mac_address(self.name, self.netifaces)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/.virtualenvs/p2pd/lib/python3.11/site-packages/p2pd/netiface_extra.py", line 30, in get_mac_address
    return netifaces.ifaddresses(name)[netifaces.AF_LINK][0]["addr"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 17
```
I was able also to run 2 different native tools to get information about interfaces, ifconfig and iproute2, with ifconfig, in android, you cannot see mac addresses and for what I know it is intended like this by android developer for recent android versions, by the way running `ip a` the information is there, I don't know for sure which command/implementation netifaces uses in linux/android, but if it uses ifconfig under the hood or same library ifconfig uses, this can be the reason it cannot access mac addresses.

For completeness I provide you the output of both commands:
ifconfig
```
Warning: cannot open /proc/net/dev (Permission denied). Limited output.
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

radio0: flags=579<UP,BROADCAST,RUNNING,ALLMULTI>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.16  netmask 255.255.255.0  broadcast 10.0.2.255
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

``` 
as you can see there is a warning that inform us about a permission denied and so a limited output

by the way `ip a` shows this:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 5a:3d:21:d3:d4:9b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::583d:21ff:fed3:d49b/64 scope link 
       valid_lft forever preferred_lft forever
3: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
5: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
8: ip6_vti0@NONE: <NOARP> mtu 1364 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
9: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
10: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
11: ip6gre0@NONE: <NOARP> mtu 1448 qdisc noop state DOWN group default qlen 1000
    link/gre6 :: brd ::
12: hwsim0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ieee802.11/radiotap 12:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
15: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:15:b2:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.16/24 brd 10.0.2.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fec0::511b:6ec4:893d:7dc7/64 scope site temporary dynamic 
       valid_lft 86093sec preferred_lft 14093sec
    inet6 fec0::d3fd:de08:e532:da1b/64 scope site dynamic mngtmpaddr stable-privacy 
       valid_lft 86093sec preferred_lft 14093sec
    inet6 fe80::4325:4963:e6e9:9766/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
17: radio0@if11: <BROADCAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 76:6a:b2:aa:57:01 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.2.15/24 brd 10.0.2.255 scope global radio0
       valid_lft forever preferred_lft forever
    inet6 fec0::8447:4a4d:3119:3789/64 scope site temporary dynamic 
       valid_lft 86093sec preferred_lft 14093sec
    inet6 fec0::746a:b2ff:feaa:5701/64 scope site dynamic mngtmpaddr 
       valid_lft 86093sec preferred_lft 14093sec
    inet6 fe80::746a:b2ff:feaa:5701/64 scope link 
       valid_lft forever preferred_lft forever
```
it seems to me that for some interfaces the mac is shown, probably is the one after `link/ether` 
tell me if you suggest something else to do, for what I know/can, I can provide you information about this android experiment.

Regards,
magowiz

**Comment by robertsdotpm** [comment] 2024-01-06 04:35
Can you show the output of netifaces.ifaddresses("whatever interface you're checking") and also netifaces.IF_LINK? What version of android are you using?

**Comment by magowiz** [comment] 2024-01-06 13:58
ok,  selected the interface on mine android device that has an address on my wifi, wlan0, so the code I run was: (I think netifaces.IF_LINK was a typo so I used AF_LINK, if I am wrong tell me)
```
import netifaces
print('first command ====')
print(netifaces.ifadress("wlan0"))
print('second command ====')
print(netifaces.AF_LINK)
```

and here it is the output
```
first command ====
{10: [{'addr': 'fe80::c16d:5573:18d4:a244%wlan0', 'netmask': 'ffff:ffff:ffff:ffff::/64'}], 2: [{'addr': '192.168.2.179', 'netmask': '255.255.255.0', 'broadcast': '192.168.2.255'}]}
second command ====
17
```

I'm using android OS 11

**Comment by robertsdotpm** [comment] 2024-01-06 14:03
Thanks, that's exactly what I need. I actually spent today working on adding better android support and I think I'm going to have to fork netifaces at this point because all the small patches I've made are adding up. I think this should be easy to fix. Will let you know when it's done.

**Comment by magowiz** [comment] 2024-01-06 14:09
I'm glad I was able to provide you useful information, thanks for your work, I saw that netifaces (vanilla one https://github.com/al45tair/netifaces , not forked) was archived, so probably if you need to introduce fixes it is a good idea the yours: forking and going on on a fork, so you don't get stuck.

Regards

**Comment by robertsdotpm** [comment] 2024-01-07 02:15
I've added a fallback for the mac function now to use a different approach if the keys don't exist for netifaces. I need to do more testing on your version of android though.

**Comment by robertsdotpm** [comment] 2024-01-07 02:45
I'm testing it now on an emulator in android studio and I can see that it may be harder to get the mac than I thought. They seem to lock down android hard. I'll see what I can do.

**Comment by robertsdotpm** [comment] 2024-01-07 03:56
Hello, I was able to reproduce the bug in an emulator and wrote a fix using a library that uses the netlink API (which has root in the kernel.) Should work better on android. Let me know if it works for you. All tests are passing for me.

**Comment by magowiz** [comment] 2024-01-07 10:45
> Hello, I was able to reproduce the bug in an emulator and wrote a fix using a library that uses the netlink API (which has root in the kernel.) Should work better on android. Let me know if it works for you. All tests are passing for me.

Of course I will give it a try and let you know, how can I try your version with the fix? Did you release it so it is currently available using pip install p2pd? Or do I need to install it from a particular branch in your repository? Maybe doing pip install git://.....? 

Then I would try this code, right?
```
from p2pd import *

async def example():
    # Start the default interface.
    init_p2pd()
    i = await Interface()
    #
    # Load additional NAT details.
    # Restrict, random port NAT assumed by default.
    
    await i.load_nat()
    #
    # Show the interface details.
    
    print(i)

if __name__ == '__main__':
    async_test(example)
```

**Comment by robertsdotpm** [comment] 2024-01-07 14:51
^ Yep, currently all the new fixes are on the 'test_sprint1' branch. Let me know if you check it out and the issue is fixed. I did try out the test suite on an emulator which showed the lack of mac address in the netiface fields. I think the issue was: in Android access to the MAC address for an interface is locked down and can't be done through standard means. So netifaces was doing that. But there's a kernel-level API that already has full permissions so it bypasses those issues. Hopefully it now works for you.

**Comment by magowiz** [comment] 2024-01-07 15:57
Hi @robertsdotpm ,
I tried this and for me, except some other errors, on mine android phone is working, I can see mac addresses:
```
/data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/src.py:5: RuntimeWarning: coroutine 'init_p2pd' was never awaited
Coroutine created at (most recent call last)
  File "/data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/src.py", line 18, in <module>
    async_test(example)
  File "/data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/lib/python3.11/site-packages/p2pd/utils.py", line 616, in async_test
    loop.run_until_complete(f())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/src.py", line 5, in example
    init_p2pd()
  init_p2pd()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
{'id': 'wlan0',
 'is_default': {2: True, 10: False},
 'mac': 'e0-cc-f8-3c-a6-df',
 'name': 'wlan0',
 'nat': {'delta': {'type': 2, 'value': 0},
         'delta_info': 'equal delta (local port == mapped port)',
         'nat_info': 'restrict port',
         'type': 5},
 'nic_no': 0,
 'rp': {2: [{'af': 2,
             'ext_ips': [{'af': 2, 'cidr': 32, 'ip': '2.235.120.73'}],
             'nic_ips': [{'af': 2, 'cidr': 32, 'ip': '192.168.2.179'}]}],
        10: []}}
exception handler
{'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-106' coro=<nat_test_workers.<locals>.worker() done, defined at /data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
exception handler
{'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-107' coro=<nat_test_workers.<locals>.worker() done, defined at /data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
exception handler
{'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-110' coro=<nat_test_workers.<locals>.worker() done, defined at /data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
exception handler
{'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-111' coro=<nat_test_workers.<locals>.worker() done, defined at /data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
exception handler
{'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-114' coro=<nat_test_workers.<locals>.worker() done, defined at /data/data/com.termux/files/home/.virtualenvs/tmp-ecb045798e88ca4/lib/python3.11/site-packages/p2pd/nat_test.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
```

What I've done:

1. create a new temporary virtualenv using mktmpenv (virtualenvwrapper) to be sure to install all from scratch
2. install p2pd with `pip install git+https://github.com/robertsdotpm/p2pd.git@test_sprint1`
3. run the code I proposed before

Is it ok for you?

**Comment by robertsdotpm** [comment] 2024-01-08 00:54
It looks like its working but try adding await before the init_p2pd func. That func is a coroutine so you need to await it.

**Comment by magowiz** [comment] 2024-01-08 07:22
> It looks like its working but try adding await before the init_p2pd func. That func is a coroutine so you need to await it.
> 
> Edit: The NAT type you have on that device is the same one I have for one of my internet connections. The delta type + NAT type makes the NAT very workable with punching algorithms.

Ok so I changed source like this:
```
from p2pd import *

async def example():
    # Start the default interface.
    await init_p2pd()
    i = await Interface()
    #
    # Load additional NAT details.
    # Restrict, random port NAT assumed by default.
    
    await i.load_nat()
    #
    # Show the interface details.
    
    print(i)

if __name__ == '__main__':
    async_test(example)
```

and this is the new output (it seems to me similar to one before but without errors):
```
{'id': 'wlan0',
 'is_default': {2: True, 10: False},
 'mac': 'e0-cc-f8-3c-a6-df',
 'name': 'wlan0',
 'nat': {'delta': {'type': 6, 'value': 0},
         'delta_info': 'random delta (local port == rand port)',
         'nat_info': 'restrict port',
         'type': 5},
 'nic_no': 0,
 'rp': {2: [{'af': 2,
             'ext_ips': [{'af': 2, 'cidr': 32, 'ip': '2.235.120.73'}],
             'nic_ips': [{'af': 2, 'cidr': 32, 'ip': '192.168.2.179'}]}],
        10: []}}
```

also in this case I can see a mac address, so it is working, what do you think?
About nat type and punching algorithms I confess that I don't know so much about that stuff :-D , but I think it should be a positive thing that mine kind of NAT is working with p2pd.

Regards
magowiz

**Comment by robertsdotpm** [comment] 2024-01-08 07:45
Hello @magowiz 

I've edited all your posts to remove the sensitive information (and I didn't save any of your details.) Let me know if I've missed anything. I do agree with your concerns though -- IPs are a scary thing to have public and in the future I'll need a way to solve these issues so people don't have to expose so much information. That will be after I write a lot more tests though.

Thanks for helping me get to the bottom of this. I'll close the issue for now but feel free to re-open it should the need arise. If you find any other bugs let me know and I'll do my best to fix them.

**Closed by robertsdotpm** 2024-01-08 07:45 UTC
